# Generated by Django 3.1.5 on 2026-04-13 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_information', '0002_auto_20260221_2129'),
        ('placement_cell', '0003_appeal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, upload_to='placement_resumes/')),
                ('about_me', models.TextField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=500, null=True)),
                ('github_url', models.URLField(blank=True, max_length=500, null=True)),
                ('portfolio_url', models.URLField(blank=True, max_length=500, null=True)),
                ('achievements', models.JSONField(blank=True, default=list, null=True)),
                ('certifications', models.JSONField(blank=True, default=list, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement_profile', to='academic_information.student')),
            ],
        ),
        migrations.CreateModel(
            name='PlacementProfileAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='placement_cell.placementprofile')),
            ],
        ),
    ]
