# Generated by Django 3.1.5 on 2026-04-14 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_information', '0002_auto_20260221_2129'),
        ('placement_cell', '0004_placementprofile_placementprofileauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.IntegerField(help_text='Year of graduation')),
                ('programme', models.CharField(blank=True, help_text='e.g. B.Tech, M.Tech, B.Des, PhD', max_length=50, null=True)),
                ('department', models.CharField(blank=True, help_text='Department at the time of graduation', max_length=100, null=True)),
                ('current_company', models.CharField(blank=True, max_length=200, null=True)),
                ('current_designation', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, max_length=2000, null=True)),
                ('verification_document', models.FileField(blank=True, help_text='Upload degree certificate or ID for verification', null=True, upload_to='placement/alumni_verification/')),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_remarks', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_alumni', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Alumni Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('topics', models.JSONField(blank=True, default=list, help_text="List of topics the mentor can help with, e.g. ['Resume Review', 'DSA', 'System Design']")),
                ('availability_slots', models.JSONField(blank=True, default=list, help_text="Preferred time-slots, e.g. [{'day':'Monday','time':'18:00-19:00'}]")),
                ('max_sessions_per_month', models.IntegerField(default=4)),
                ('bio', models.TextField(blank=True, help_text='Short mentorship-specific bio / what you can help with', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumni', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_profile', to='placement_cell.alumniprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, help_text="Student's message to the mentor", max_length=1000, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('meeting_link', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('mentor_notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='placement_cell.mentorshipprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_sessions', to='academic_information.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('role_title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=3000)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('referral_link', models.URLField(blank=True, help_text='Application / referral link', max_length=500, null=True)),
                ('ctc_range', models.CharField(blank=True, help_text='e.g. 12-18 LPA', max_length=100, null=True)),
                ('eligible_programmes', models.CharField(blank=True, help_text='Comma-separated: B.Tech, M.Tech, B.Des, PhD', max_length=200, null=True)),
                ('eligible_branches', models.CharField(blank=True, help_text='Comma-separated: CSE, ECE, ME, DESIGN', max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='placement_cell.alumniprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
