# Generated by Django 3.1.5 on 2026-04-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_cell', '0005_alumniprofile_jobreferral_mentorshipprofile_mentorshipsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewschedule',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Duration of the interview slot in minutes'),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Auto-computed from time_slot + duration_minutes', null=True),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='reschedule_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this interview has been rescheduled (max 2)'),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='round_number',
            field=models.PositiveIntegerField(default=1, help_text='Interview round number (1, 2, 3...)'),
        ),
        migrations.AlterField(
            model_name='interviewpanel',
            name='result',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted')], default='PENDING', help_text='PENDING / SELECTED / REJECTED / WAITLISTED', max_length=20),
        ),
    ]
