# Generated by Django 3.1.5 on 2026-04-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_cell', '0009_jobposting_compensation_and_jd'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='applicant_email',
            field=models.EmailField(blank=True, help_text='Professional email captured from PlacementProfile at apply time', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='applicant_github',
            field=models.URLField(blank=True, help_text='GitHub URL captured from PlacementProfile at apply time', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='applicant_linkedin',
            field=models.URLField(blank=True, help_text='LinkedIn URL captured from PlacementProfile at apply time', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='placementprofile',
            name='professional_email',
            field=models.EmailField(blank=True, help_text='Preferred contact email used in placement applications.', max_length=254, null=True),
        ),
    ]
