# Generated by Django 3.1.5 on 2026-04-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_cell', '0010_placement_profile_email_and_application_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='attachment_label',
            field=models.CharField(blank=True, help_text="Optional display label for the attachment link (e.g. 'Registration form')", max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='attachment_link',
            field=models.URLField(blank=True, help_text='Optional external link attached to the notice (Drive, JD, registration form, etc.)', max_length=1000, null=True),
        ),
    ]
