# Generated by Django 3.1.5 on 2026-04-26 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0002_auto_20260221_2129'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('placement_cell', '0011_announcement_attachment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementprofile',
            name='apply_override',
            field=models.BooleanField(default=False, help_text='If true, the student may apply even after being marked placed.'),
        ),
        migrations.AddField(
            model_name='placementprofile',
            name='apply_override_remarks',
            field=models.TextField(blank=True, help_text='Reason recorded by TPO when granting an apply override.', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='PlacementClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PLACEMENT', 'Placement'), ('INTERNSHIP', 'Internship')], max_length=20)),
                ('company_name', models.CharField(max_length=200)),
                ('role_title', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('compensation_amount', models.DecimalField(blank=True, decimal_places=2, help_text='LPA for placements, ₹/month for internships', max_digits=10, null=True)),
                ('duration_months', models.PositiveSmallIntegerField(blank=True, help_text='Internship duration in months (only used when kind=INTERNSHIP)', null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('OFFCAMPUS', 'Off-campus'), ('ONCAMPUS', 'On-campus / Through PCMS'), ('REFERRAL', 'Referral'), ('OTHER', 'Other')], default='OFFCAMPUS', max_length=20)),
                ('proof_link', models.URLField(blank=True, help_text='Optional link to offer letter / mail screenshot', max_length=1000, null=True)),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('verification_remarks', models.TextField(blank=True, max_length=1000, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who originally submitted this claim (student or TPO).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_placement_claims', to=settings.AUTH_USER_MODEL)),
                ('related_offer', models.ForeignKey(blank=True, help_text='Set automatically when the claim originates from an accepted JobOffer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_claims', to='placement_cell.joboffer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_claims', to='academic_information.student')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_placement_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
